# Credit: Pheubel - VSH2 Continuous Integration.
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_linux:
    name: (Linux) Compile SourcePawn ${{matrix.sm_version}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sm_version: ['1.10']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SourcePawn Compiler ${{ matrix.sm_version }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm_version }}

      - name: Setup Environment
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTS_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV
        
      - name: Fetch plugin dependencies
        run: |
          wget https://raw.githubusercontent.com/redsunservers/VSH-Rewrite/master/addons/sourcemod/scripting/include/saxtonhale.inc -P $includePath
          wget https://raw.githubusercontent.com/peace-maker/DHooks2/dynhooks/sourcemod_files/scripting/include/dhooks.inc -P $includePath
          wget https://raw.githubusercontent.com/nosoop/SM-TFEconData/master/scripting/include/tf_econ_data.inc -P $includePath
          wget https://raw.githubusercontent.com/FlaminSarge/tf2attributes/master/tf2attributes.inc -P $includePath
          wget https://raw.githubusercontent.com/Teamkiller324/Updater/main/scripting/include/updater.inc -P $includePath
        
      - name: Compile Plugin
        run: |
          spcomp $SCRIPTS_PATH/saxtonhale_bosses.sp -i$SCRIPTS_PATH/include -O2 -v2 -o $SOURCEMOD_PATH/plugins/saxtonhale_bosses.smx

  upload_source:
    name: Upload Source
    needs: build_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Package source code
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          zip -r 'Source code.zip' ./addons
          tar cvf 'Source code.tar' addons
      
      # this will upload a zip with a zip and a tar file, this is to avoid being rate liited by the github API
      - name: Upload source code
        uses: actions/upload-artifact@v2
        with:
          name: VSH-Bosses Source
          if-no-files-found: error
          path: |
            Source code.zip
            Source code.tar