# Credit: Pheubel - VSH2 Continuous Integration.
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_linux:
    name: (Linux) Compile SourcePawn ${{matrix.sm_version}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sm_version: ['1.10']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          bash scripts/install.sh
        
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp saxtonhale_bosses.sp -o ../plugins/saxtonhale_bosses.smx
        
      - name: Pushes saxtonhale_bosses.smx
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build/addons/sourcemod/plugins/saxtonhale_bosses.smx'
          destination_repo: 'TheRefuge/VSH-Bosses'
          destination_folder: 'addons/sourcemod/plugins'
          user_email: 'aidan.sanders1316@gmail.com'
          user_name: 'asanders'
          commit_message: 'Plugin Update'